spring:
  profiles:
    active: dev
  thymeleaf:
    cache: true
    check-template-location: true
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    excluded-view-names:
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    template-resolver-order:
  redis:
    host: 119.29.105.15
    database: 0
    port: 6379
    password: 'redis123456'
    jedis:
      pool:
        max-wait: -1
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 5000
