spring:
  profiles:
    active: dev
  thymeleaf:
    cache: true
    check-template-location: true
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    excluded-view-names:
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    template-resolver-order:
  redis:
    host: 119.29.105.15
    database: 0
    port: 6379
    password: 'redis123456'
    jedis:
      pool:
        max-wait: -1
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 5000
  data:
    mongodb:
      uri: mongodb://root:root@119.29.105.15:27017/test
      option:
        min-connection-per-host: 0
        max-connection-per-host: 100
        threads-allowed-to-block-for-connection-multiplier: 5
        server-selection-timeout: 30000
        max-wait-time: 120000
        max-connection-idle-time: 0
        max-connection-life-time: 0
        connect-timeout: 10000
        socket-timeout: 0
        socket-keep-alive: false
        ssl-enabled: false
        ssl-invalid-host-name-allowed: false
        always-use-m-beans: false
        heartbeat-socket-timeout: 20000
        heartbeat-connect-timeout: 20000
        min-heartbeat-frequency: 500
        heartbeat-frequency: 10000
        local-threshold: 15
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      #连接池配置
      url: jdbc:mysql://119.29.105.15:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false
      username: root
      password: '%Om2mnlT'
      initial-size: 5
      min-idle: 5
      max-active: 20
      #连接等待超时时间
      max-wait: 60000
      #配置隔多久进行一次检测(检测可以关闭的空闲连接)
      time-between-eviction-runs-millis: 60000
      #配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  output:
    ansi:
      enabled: detect
  cache:
    ehcache:
      config: classpath:ehcache.xml
  aop:
    auto: true
    proxy-target-class: false
  messages:
    basename: i18n/messages
    cache-duration: 3600
    encoding: UTF-8
debug: true
logging:
  file: web.log
  path: D:\logs
  level:
    root: WARN
    com:
      xxh: DEBUG

example:
  service:
    enabled: true
    prefix: '####'
    suffix: '@@@@'
jasypt.encryptor.password: 123456